import type { Researcher, ResearchProject, Publication, Facility, ResearchData } from "./types";

const researchers: Researcher[] = [
  {
    id: "r1",
    slug: "a-nwosu",
    name: "Dr. A. Nwosu",
    role: "Senior Lecturer",
    unitType: "department",
    unitSlug: "crop-science",
    unitName: "Crop Science",
    orcid: "0000-0002-1111-2222",
    bio: "Works on drought-tolerant cassava and yam breeding across three agro-ecological zones.",
    contactPublished: true,
    contactEmail: "a.nwosu@mouau.edu.ng",
  },
  {
    id: "r2",
    slug: "b-okafor",
    name: "Dr. B. Okafor",
    role: "Senior Lecturer",
    unitType: "department",
    unitSlug: "soil-science",
    unitName: "Soil Science",
    orcid: "0000-0002-3333-4444",
    bio: "Researches soil fertility management under climate-variable rainfall.",
    contactPublished: true,
    contactEmail: "b.okafor@mouau.edu.ng",
  },
  {
    id: "r3",
    slug: "biotech-director",
    name: "Dr. (Director, Biotechnology Research)",
    role: "Centre Director",
    unitType: "centre",
    unitSlug: "centre-for-biotechnology-research",
    unitName: "Centre for Biotechnology Research",
    orcid: "0000-0002-5555-6666",
    bio: "Leads genomics and tissue-culture research for tropical crop improvement.",
    contactPublished: false,
  },
];

const projects: ResearchProject[] = [
  {
    id: "p1",
    slug: "drought-tolerant-cassava-yam",
    title: "Field-testing drought-tolerant cassava and yam cultivars",
    researcherSlugs: ["a-nwosu", "b-okafor"],
    funder: "Federal Ministry of Agriculture",
    startDate: "2023-01-01",
    impactNarrative: "Cross-college trials spanning three agro-ecological zones are shortening the path from lab result to a cultivar smallholder farmers can actually plant.",
    sdgTags: [2, 13],
  },
  {
    id: "p2",
    slug: "soil-fertility-mapping-abia",
    title: "Soil fertility mapping across Abia State farming communities",
    researcherSlugs: ["b-okafor"],
    funder: "MOUAU Institutional Research Grant",
    startDate: "2024-03-01",
    impactNarrative: "Producing an open soil-fertility map extension officers can use for input recommendations.",
    sdgTags: [2, 15],
  },
  {
    id: "p3",
    slug: "tissue-culture-yam-multiplication",
    title: "Rapid tissue-culture multiplication of disease-free yam seedlings",
    researcherSlugs: ["biotech-director"],
    funder: "International Institute of Tropical Agriculture (partner)",
    startDate: "2022-09-01",
    impactNarrative: "Scaling clean planting material to reduce yield losses from seed-borne disease.",
    sdgTags: [2],
  },
];

const publications: Publication[] = [
  {
    id: "pub1",
    slug: "drought-tolerance-cassava-2026",
    title: "Yield stability of drought-tolerant cassava cultivars under variable rainfall",
    authorSlugs: ["a-nwosu"],
    externalAuthors: ["O. Adebayo (IITA)"],
    journal: "African Journal of Agricultural Research",
    year: 2026,
    doi: "10.5555/ajar.2026.0142",
    abstract: "Five-year field trial results across three agro-ecological zones in southeastern Nigeria.",
  },
  {
    id: "pub2",
    slug: "soil-fertility-variability-abia-2025",
    title: "Spatial variability of soil fertility indicators in Abia State smallholder farms",
    authorSlugs: ["b-okafor"],
    journal: "Nigerian Journal of Soil Science",
    year: 2025,
    doi: "10.5555/njss.2025.0087",
    abstract: "GIS-based mapping of nitrogen, phosphorus and organic matter across sampled farms.",
  },
  {
    id: "pub3",
    slug: "tissue-culture-yam-protocol-2025",
    title: "An optimized tissue-culture protocol for disease-free yam seedling multiplication",
    authorSlugs: ["biotech-director"],
    journal: "Journal of Tropical Biotechnology",
    year: 2025,
    doi: "10.5555/jtb.2025.0231",
    abstract: "A refined micropropagation protocol reducing multiplication time by 30%.",
  },
];

const facilities: Facility[] = [
  { id: "f1", slug: "teaching-research-farm", name: "Teaching & Research Farm", ownerType: "college", ownerSlug: "college-of-agriculture", location: "Umudike main campus", equipment: ["Irrigation plots", "Weather station"], services: "Field trial hosting for staff and postgraduate research." },
  { id: "f2", slug: "soil-science-laboratory", name: "Soil Science Laboratory", ownerType: "college", ownerSlug: "college-of-agriculture", location: "College of Agriculture building", equipment: ["Soil nutrient analyzer", "pH meters"], managerSlug: "b-okafor", services: "Soil sample analysis for research and extension." },
  { id: "f3", slug: "seed-technology-unit", name: "Seed Technology Unit", ownerType: "college", ownerSlug: "college-of-agriculture", location: "College of Agriculture building", equipment: ["Seed viability testing kit"], services: "Seed quality testing and certification support." },
  { id: "f4", slug: "veterinary-teaching-hospital", name: "Veterinary Teaching Hospital", ownerType: "college", ownerSlug: "college-of-veterinary-medicine", location: "College of Veterinary Medicine", equipment: ["Surgical suite", "Diagnostic imaging"], services: "Clinical training and animal health services." },
  { id: "f5", slug: "diagnostic-laboratory", name: "Diagnostic Laboratory", ownerType: "college", ownerSlug: "college-of-veterinary-medicine", location: "College of Veterinary Medicine", equipment: ["PCR machine", "Microscopy suite"], services: "Disease diagnosis and pathology research." },
  { id: "f6", slug: "forestry-nursery", name: "Forestry Nursery", ownerType: "college", ownerSlug: "college-of-natural-resources-and-environmental-management", location: "CNREM grounds", equipment: ["Propagation beds"], services: "Seedling propagation for forestry research and outreach." },
  { id: "f7", slug: "fisheries-aquaculture-unit", name: "Fisheries & Aquaculture Unit", ownerType: "college", ownerSlug: "college-of-natural-resources-and-environmental-management", location: "CNREM grounds", equipment: ["Fish ponds", "Water quality testing kit"], services: "Aquaculture research and demonstration." },
  { id: "f8", slug: "food-processing-pilot-plant", name: "Food Processing Pilot Plant", ownerType: "college", ownerSlug: "college-of-applied-engineering", location: "CAFSE building", equipment: ["Pilot-scale dryer", "Milling unit"], services: "Food product development and processing trials." },
  { id: "f9", slug: "bioresources-engineering-workshop", name: "Bioresources Engineering Workshop", ownerType: "college", ownerSlug: "college-of-applied-engineering", location: "CAFSE building", equipment: ["Fabrication workshop"], services: "Agricultural equipment design and testing." },
  { id: "f10", slug: "agribusiness-case-studies-lab", name: "Agribusiness Case Studies Lab", ownerType: "college", ownerSlug: "college-of-management-sciences", location: "College of Management Sciences", equipment: ["Case study library", "Computer lab"], services: "Applied agribusiness research and teaching." },
  { id: "f11", slug: "rural-demonstration-plots", name: "Rural Demonstration Plots", ownerType: "centre", ownerSlug: "centre-for-agricultural-extension", location: "Umudike outreach site", equipment: ["Demonstration plots"], services: "Farmer field days and extension demonstrations." },
  { id: "f12", slug: "extension-training-hall", name: "Extension Training Hall", ownerType: "centre", ownerSlug: "centre-for-agricultural-extension", location: "Umudike outreach site", equipment: ["Training hall (120 capacity)"], services: "Extension officer and farmer training sessions." },
  { id: "f13", slug: "molecular-biology-laboratory", name: "Molecular Biology Laboratory", ownerType: "centre", ownerSlug: "centre-for-biotechnology-research", location: "Biotechnology Centre", equipment: ["PCR machines", "Gel electrophoresis"], managerSlug: "biotech-director", services: "Genomics and molecular research support." },
  { id: "f14", slug: "tissue-culture-unit", name: "Tissue Culture Unit", ownerType: "centre", ownerSlug: "centre-for-biotechnology-research", location: "Biotechnology Centre", equipment: ["Laminar flow hoods", "Growth chambers"], managerSlug: "biotech-director", services: "Plant tissue culture and micropropagation." },
  { id: "f15", slug: "climate-simulation-plots", name: "Climate Simulation Plots", ownerType: "centre", ownerSlug: "centre-for-climate-smart-agriculture", location: "Umudike research station", equipment: ["Rainout shelters"], services: "Controlled-condition climate resilience trials." },
];

export const mockResearchData: ResearchData = { researchers, projects, publications, facilities };
